"""Add remaining untranslated string keys to translations.json."""
import json, os

PATH = os.path.join(os.path.dirname(__file__), "translations.json")
with open(PATH, encoding="utf-8") as f:
    data = json.load(f)

NEW = {
    # ── Metadata Editor ──────────────────────────────────────────────────
    "METADATA_MSG_NO_FILE_TITLE": {
        "value": "Metadata", "en": "Metadata",
        "es": "Metadatos", "fr": "Métadonnées", "de": "Metadaten",
        "pt-BR": "Metadados", "it": "Metadati", "nl": "Metagegevens",
        "ru": "Метаданные", "ja": "メタデータ", "zh-CN": "元数据",
        "ko": "메타데이터", "pl": "Metadane", "tr": "Meta veriler",
        "ar": "البيانات الوصفية", "hi": "मेटाडेटा", "sv": "Metadata",
    },

    # ── STT Translation Dialog ────────────────────────────────────────────
    "STT_TR_DIALOG_TITLE": {
        "value": "Translation → {lang}", "en": "Translation → {lang}",
        "es": "Traducción → {lang}", "fr": "Traduction → {lang}",
        "de": "Übersetzung → {lang}", "pt-BR": "Tradução → {lang}",
        "it": "Traduzione → {lang}", "nl": "Vertaling → {lang}",
        "ru": "Перевод → {lang}", "ja": "翻訳 → {lang}",
        "zh-CN": "翻译 → {lang}", "ko": "번역 → {lang}",
        "pl": "Tłumaczenie → {lang}", "tr": "Çeviri → {lang}",
        "ar": "ترجمة → {lang}", "hi": "अनुवाद → {lang}",
        "sv": "Översättning → {lang}",
    },
    "STT_TR_DIALOG_HEADING": {
        "value": "Translation  →  {lang}", "en": "Translation  →  {lang}",
        "es": "Traducción  →  {lang}", "fr": "Traduction  →  {lang}",
        "de": "Übersetzung  →  {lang}", "pt-BR": "Tradução  →  {lang}",
        "it": "Traduzione  →  {lang}", "nl": "Vertaling  →  {lang}",
        "ru": "Перевод  →  {lang}", "ja": "翻訳  →  {lang}",
        "zh-CN": "翻译  →  {lang}", "ko": "번역  →  {lang}",
        "pl": "Tłumaczenie  →  {lang}", "tr": "Çeviri  →  {lang}",
        "ar": "ترجمة  →  {lang}", "hi": "अनुवाद  →  {lang}",
        "sv": "Översättning  →  {lang}",
    },
    "STT_TR_COLUMN_ORIGINAL": {
        "value": "Original", "en": "Original",
        "es": "Original", "fr": "Original", "de": "Original",
        "pt-BR": "Original", "it": "Originale", "nl": "Origineel",
        "ru": "Оригинал", "ja": "原文", "zh-CN": "原文",
        "ko": "원본", "pl": "Oryginał", "tr": "Orijinal",
        "ar": "الأصلي", "hi": "मूल", "sv": "Original",
    },
    "STT_TR_COLUMN_TRANSLATED": {
        "value": "Translated → {lang}", "en": "Translated → {lang}",
        "es": "Traducido → {lang}", "fr": "Traduit → {lang}",
        "de": "Übersetzt → {lang}", "pt-BR": "Traduzido → {lang}",
        "it": "Tradotto → {lang}", "nl": "Vertaald → {lang}",
        "ru": "Перевод → {lang}", "ja": "翻訳済み → {lang}",
        "zh-CN": "已翻译 → {lang}", "ko": "번역됨 → {lang}",
        "pl": "Przetłumaczone → {lang}", "tr": "Çevrildi → {lang}",
        "ar": "مترجم → {lang}", "hi": "अनुवादित → {lang}",
        "sv": "Översatt → {lang}",
    },
    "STT_TR_SAVE_DIALOG_TITLE": {
        "value": "Save Translated Transcript", "en": "Save Translated Transcript",
        "es": "Guardar transcripción traducida", "fr": "Enregistrer la transcription traduite",
        "de": "Übersetzte Transkription speichern", "pt-BR": "Salvar transcrição traduzida",
        "it": "Salva trascrizione tradotta", "nl": "Vertaalde transcriptie opslaan",
        "ru": "Сохранить переведённую транскрипцию", "ja": "翻訳済み文字起こしを保存",
        "zh-CN": "保存已翻译的转录", "ko": "번역된 전사 저장",
        "pl": "Zapisz przetłumaczoną transkrypcję", "tr": "Çevrilmiş metni kaydet",
        "ar": "حفظ النص المترجم", "hi": "अनुवादित ट्रांसक्रिप्ट सेव करें",
        "sv": "Spara översatt transkription",
    },
    "STT_TR_SAVED_TITLE": {
        "value": "Saved", "en": "Saved",
        "es": "Guardado", "fr": "Enregistré", "de": "Gespeichert",
        "pt-BR": "Salvo", "it": "Salvato", "nl": "Opgeslagen",
        "ru": "Сохранено", "ja": "保存済み", "zh-CN": "已保存",
        "ko": "저장됨", "pl": "Zapisano", "tr": "Kaydedildi",
        "ar": "تم الحفظ", "hi": "सेव हो गया", "sv": "Sparad",
    },
    "STT_TR_SAVED_BODY": {
        "value": "Saved to:\n{path}", "en": "Saved to:\n{path}",
        "es": "Guardado en:\n{path}", "fr": "Enregistré dans:\n{path}",
        "de": "Gespeichert in:\n{path}", "pt-BR": "Salvo em:\n{path}",
        "it": "Salvato in:\n{path}", "nl": "Opgeslagen in:\n{path}",
        "ru": "Сохранено в:\n{path}", "ja": "保存先:\n{path}",
        "zh-CN": "保存至:\n{path}", "ko": "저장됨:\n{path}",
        "pl": "Zapisano w:\n{path}", "tr": "Kaydedildi:\n{path}",
        "ar": "تم الحفظ في:\n{path}", "hi": "यहाँ सेव हुआ:\n{path}",
        "sv": "Sparad till:\n{path}",
    },
    "STT_TR_SEND_ERROR": {
        "value": "Could not send to Speech Lab:\n{error}",
        "en": "Could not send to Speech Lab:\n{error}",
        "es": "No se pudo enviar al Laboratorio de voz:\n{error}",
        "fr": "Impossible d'envoyer au Lab Vocal:\n{error}",
        "de": "Konnte nicht an Speech Lab gesendet werden:\n{error}",
        "pt-BR": "Não foi possível enviar ao Lab de Fala:\n{error}",
        "it": "Impossibile inviare al Lab Vocale:\n{error}",
        "nl": "Kan niet naar Speech Lab sturen:\n{error}",
        "ru": "Не удалось отправить в Speech Lab:\n{error}",
        "ja": "Speech Labへの送信に失敗:\n{error}",
        "zh-CN": "无法发送到语音实验室:\n{error}",
        "ko": "Speech Lab으로 전송 실패:\n{error}",
        "pl": "Nie można wysłać do Speech Lab:\n{error}",
        "tr": "Speech Lab'a gönderilemedi:\n{error}",
        "ar": "تعذر الإرسال إلى مختبر الكلام:\n{error}",
        "hi": "Speech Lab को नहीं भेजा जा सका:\n{error}",
        "sv": "Kunde inte skicka till Speech Lab:\n{error}",
    },
    "STT_TR_BTN_SAVE": {
        "value": "💾  Save Translated", "en": "💾  Save Translated",
        "es": "💾  Guardar traducción", "fr": "💾  Enregistrer la traduction",
        "de": "💾  Übersetzung speichern", "pt-BR": "💾  Salvar tradução",
        "it": "💾  Salva traduzione", "nl": "💾  Vertaling opslaan",
        "ru": "💾  Сохранить перевод", "ja": "💾  翻訳を保存",
        "zh-CN": "💾  保存翻译", "ko": "💾  번역 저장",
        "pl": "💾  Zapisz tłumaczenie", "tr": "💾  Çeviriyi kaydet",
        "ar": "💾  حفظ الترجمة", "hi": "💾  अनुवाद सेव करें",
        "sv": "💾  Spara översättning",
    },
    "STT_TR_BTN_SEND_ORIGINAL": {
        "value": "➕  Send Original to Speech Lab",
        "en": "➕  Send Original to Speech Lab",
        "es": "➕  Enviar original al Lab de voz",
        "fr": "➕  Envoyer l'original au Lab Vocal",
        "de": "➕  Original an Speech Lab senden",
        "pt-BR": "➕  Enviar original ao Lab de Fala",
        "it": "➕  Invia originale al Lab Vocale",
        "nl": "➕  Origineel naar Speech Lab sturen",
        "ru": "➕  Отправить оригинал в Speech Lab",
        "ja": "➕  原文をSpeech Labへ送る",
        "zh-CN": "➕  将原文发送到语音实验室",
        "ko": "➕  원본을 Speech Lab으로 보내기",
        "pl": "➕  Wyślij oryginał do Speech Lab",
        "tr": "➕  Orijinali Speech Lab'a gönder",
        "ar": "➕  إرسال الأصل إلى مختبر الكلام",
        "hi": "➕  मूल को Speech Lab भेजें",
        "sv": "➕  Skicka original till Speech Lab",
    },
    "STT_TR_BTN_SEND_TRANSLATED": {
        "value": "➕  Send Translation to Speech Lab",
        "en": "➕  Send Translation to Speech Lab",
        "es": "➕  Enviar traducción al Lab de voz",
        "fr": "➕  Envoyer la traduction au Lab Vocal",
        "de": "➕  Übersetzung an Speech Lab senden",
        "pt-BR": "➕  Enviar tradução ao Lab de Fala",
        "it": "➕  Invia traduzione al Lab Vocale",
        "nl": "➕  Vertaling naar Speech Lab sturen",
        "ru": "➕  Отправить перевод в Speech Lab",
        "ja": "➕  翻訳をSpeech Labへ送る",
        "zh-CN": "➕  将翻译发送到语音实验室",
        "ko": "➕  번역을 Speech Lab으로 보내기",
        "pl": "➕  Wyślij tłumaczenie do Speech Lab",
        "tr": "➕  Çeviriyi Speech Lab'a gönder",
        "ar": "➕  إرسال الترجمة إلى مختبر الكلام",
        "hi": "➕  अनुवाद को Speech Lab भेजें",
        "sv": "➕  Skicka översättning till Speech Lab",
    },
    "COMMON_BTN_CLOSE": {
        "value": "✕  Close", "en": "✕  Close",
        "es": "✕  Cerrar", "fr": "✕  Fermer", "de": "✕  Schließen",
        "pt-BR": "✕  Fechar", "it": "✕  Chiudi", "nl": "✕  Sluiten",
        "ru": "✕  Закрыть", "ja": "✕  閉じる", "zh-CN": "✕  关闭",
        "ko": "✕  닫기", "pl": "✕  Zamknij", "tr": "✕  Kapat",
        "ar": "✕  إغلاق", "hi": "✕  बंद करें", "sv": "✕  Stäng",
    },

    # ── Voice Lab clone messages ──────────────────────────────────────────
    "VOICE_LAB_MSG_CLONE_NO_RECORDING": {
        "value": "No recording available.",
        "en": "No recording available.",
        "es": "No hay grabación disponible.",
        "fr": "Aucun enregistrement disponible.",
        "de": "Keine Aufnahme verfügbar.",
        "pt-BR": "Nenhuma gravação disponível.",
        "it": "Nessuna registrazione disponibile.",
        "nl": "Geen opname beschikbaar.",
        "ru": "Запись недоступна.",
        "ja": "録音がありません。",
        "zh-CN": "没有可用的录音。",
        "ko": "사용 가능한 녹음이 없습니다.",
        "pl": "Brak dostępnego nagrania.",
        "tr": "Kullanılabilir kayıt yok.",
        "ar": "لا يوجد تسجيل متاح.",
        "hi": "कोई रिकॉर्डिंग उपलब्ध नहीं है।",
        "sv": "Ingen inspelning tillgänglig.",
    },
    "VOICE_LAB_MSG_CLONE_NAME_EXISTS": {
        "value": "Voice \"{name}\" already exists.",
        "en": "Voice \"{name}\" already exists.",
        "es": "La voz \"{name}\" ya existe.",
        "fr": "La voix \"{name}\" existe déjà.",
        "de": "Stimme \"{name}\" existiert bereits.",
        "pt-BR": "A voz \"{name}\" já existe.",
        "it": "La voce \"{name}\" esiste già.",
        "nl": "Stem \"{name}\" bestaat al.",
        "ru": "Голос \"{name}\" уже существует.",
        "ja": "ボイス「{name}」はすでに存在します。",
        "zh-CN": '声音"{name}"已存在。',
        "ko": "보이스 \"{name}\"이(가) 이미 존재합니다.",
        "pl": "Głos \"{name}\" już istnieje.",
        "tr": "\"{name}\" sesi zaten mevcut.",
        "ar": "الصوت \"{name}\" موجود بالفعل.",
        "hi": "आवाज़ \"{name}\" पहले से मौजूद है।",
        "sv": "Röst \"{name}\" finns redan.",
    },

    # ── Listen Lab messages ───────────────────────────────────────────────
    "LISTEN_LAB_MSG_FILE_NOT_FOUND": {
        "value": "File not found:\n{path}",
        "en": "File not found:\n{path}",
        "es": "Archivo no encontrado:\n{path}",
        "fr": "Fichier introuvable:\n{path}",
        "de": "Datei nicht gefunden:\n{path}",
        "pt-BR": "Arquivo não encontrado:\n{path}",
        "it": "File non trovato:\n{path}",
        "nl": "Bestand niet gevonden:\n{path}",
        "ru": "Файл не найден:\n{path}",
        "ja": "ファイルが見つかりません:\n{path}",
        "zh-CN": "文件未找到:\n{path}",
        "ko": "파일을 찾을 수 없습니다:\n{path}",
        "pl": "Nie znaleziono pliku:\n{path}",
        "tr": "Dosya bulunamadı:\n{path}",
        "ar": "الملف غير موجود:\n{path}",
        "hi": "फ़ाइल नहीं मिली:\n{path}",
        "sv": "Filen hittades inte:\n{path}",
    },
    "LISTEN_LAB_MSG_FFMPEG_ERROR": {
        "value": "Cannot start FFmpeg:\n{error}",
        "en": "Cannot start FFmpeg:\n{error}",
        "es": "No se puede iniciar FFmpeg:\n{error}",
        "fr": "Impossible de démarrer FFmpeg:\n{error}",
        "de": "FFmpeg kann nicht gestartet werden:\n{error}",
        "pt-BR": "Não foi possível iniciar o FFmpeg:\n{error}",
        "it": "Impossibile avviare FFmpeg:\n{error}",
        "nl": "Kan FFmpeg niet starten:\n{error}",
        "ru": "Не удалось запустить FFmpeg:\n{error}",
        "ja": "FFmpegを起動できません:\n{error}",
        "zh-CN": "无法启动 FFmpeg:\n{error}",
        "ko": "FFmpeg을 시작할 수 없습니다:\n{error}",
        "pl": "Nie można uruchomić FFmpeg:\n{error}",
        "tr": "FFmpeg başlatılamıyor:\n{error}",
        "ar": "تعذر تشغيل FFmpeg:\n{error}",
        "hi": "FFmpeg शुरू नहीं हो सका:\n{error}",
        "sv": "Kan inte starta FFmpeg:\n{error}",
    },
    "LISTEN_LAB_MSG_QWEN_NOT_READY": {
        "value": "Qwen model not ready.\n\nGo to Settings → download the Qwen model, then try again.",
        "en": "Qwen model not ready.\n\nGo to Settings → download the Qwen model, then try again.",
        "es": "Modelo Qwen no listo.\n\nVe a Configuración → descarga el modelo Qwen e inténtalo de nuevo.",
        "fr": "Modèle Qwen pas prêt.\n\nAllez dans Paramètres → téléchargez le modèle Qwen, puis réessayez.",
        "de": "Qwen-Modell nicht bereit.\n\nGehen Sie zu Einstellungen → laden Sie das Qwen-Modell herunter und versuchen Sie es erneut.",
        "pt-BR": "Modelo Qwen não está pronto.\n\nVá para Configurações → baixe o modelo Qwen e tente novamente.",
        "it": "Modello Qwen non pronto.\n\nVai su Impostazioni → scarica il modello Qwen e riprova.",
        "nl": "Qwen-model niet klaar.\n\nGa naar Instellingen → download het Qwen-model en probeer het opnieuw.",
        "ru": "Модель Qwen не готова.\n\nПерейдите в Настройки → загрузите модель Qwen и попробуйте снова.",
        "ja": "Qwenモデルが準備できていません。\n\n設定→QwenモデルをダウンロードしてからもういちどO試みてください。",
        "zh-CN": "Qwen 模型尚未就绪。\n\n请前往设置 → 下载 Qwen 模型，然后重试。",
        "ko": "Qwen 모델이 준비되지 않았습니다.\n\n설정 → Qwen 모델 다운로드 후 다시 시도하세요.",
        "pl": "Model Qwen nie jest gotowy.\n\nPrzejdź do Ustawień → pobierz model Qwen i spróbuj ponownie.",
        "tr": "Qwen modeli hazır değil.\n\nAyarlar → Qwen modelini indir, ardından tekrar deneyin.",
        "ar": "نموذج Qwen غير جاهز.\n\nاذهب إلى الإعدادات → نزّل نموذج Qwen ثم أعد المحاولة.",
        "hi": "Qwen मॉडल तैयार नहीं है।\n\nसेटिंग्स → Qwen मॉडल डाउनलोड करें, फिर दोबारा कोशिश करें।",
        "sv": "Qwen-modellen är inte redo.\n\nGå till Inställningar → ladda ner Qwen-modellen och försök igen.",
    },
    "LISTEN_LAB_MSG_SAVE_FAILED": {
        "value": "Export failed:\n{error}",
        "en": "Export failed:\n{error}",
        "es": "Error al exportar:\n{error}",
        "fr": "Échec de l'exportation:\n{error}",
        "de": "Export fehlgeschlagen:\n{error}",
        "pt-BR": "Falha na exportação:\n{error}",
        "it": "Esportazione fallita:\n{error}",
        "nl": "Exporteren mislukt:\n{error}",
        "ru": "Ошибка экспорта:\n{error}",
        "ja": "エクスポート失敗:\n{error}",
        "zh-CN": "导出失败:\n{error}",
        "ko": "내보내기 실패:\n{error}",
        "pl": "Eksport nie powiódł się:\n{error}",
        "tr": "Dışa aktarma başarısız:\n{error}",
        "ar": "فشل التصدير:\n{error}",
        "hi": "एक्सपोर्ट विफल:\n{error}",
        "sv": "Export misslyckades:\n{error}",
    },

    # ── Speech Lab ────────────────────────────────────────────────────────
    "SPEECH_LAB_MSG_NO_AUDIO_SEL": {
        "value": "No selected items have generated audio yet.",
        "en": "No selected items have generated audio yet.",
        "es": "Ningún elemento seleccionado ha generado audio todavía.",
        "fr": "Aucun élément sélectionné n'a encore généré d'audio.",
        "de": "Kein ausgewähltes Element hat noch Audio generiert.",
        "pt-BR": "Nenhum item selecionado gerou áudio ainda.",
        "it": "Nessun elemento selezionato ha ancora generato audio.",
        "nl": "Geen geselecteerde items hebben nog audio gegenereerd.",
        "ru": "Ни один из выбранных элементов ещё не создал аудио.",
        "ja": "選択したアイテムにはまだ音声がありません。",
        "zh-CN": "所选项目尚未生成任何音频。",
        "ko": "선택된 항목 중 아직 오디오를 생성한 것이 없습니다.",
        "pl": "Żaden wybrany element nie wygenerował jeszcze dźwięku.",
        "tr": "Seçilen öğelerin hiçbiri henüz ses oluşturmadı.",
        "ar": "لم تُنشئ أي من العناصر المحددة صوتاً بعد.",
        "hi": "किसी भी चुने गए आइटम ने अभी तक ऑडियो नहीं बनाया है।",
        "sv": "Inga valda objekt har genererat ljud än.",
    },

    # ── STT / Transcribe Lab ─────────────────────────────────────────────
    "STT_MSG_UNSUPPORTED_FORMAT": {
        "value": "Unsupported audio format: {ext}",
        "en": "Unsupported audio format: {ext}",
        "es": "Formato de audio no compatible: {ext}",
        "fr": "Format audio non pris en charge: {ext}",
        "de": "Nicht unterstütztes Audioformat: {ext}",
        "pt-BR": "Formato de áudio não suportado: {ext}",
        "it": "Formato audio non supportato: {ext}",
        "nl": "Niet-ondersteund audioformaat: {ext}",
        "ru": "Неподдерживаемый аудиоформат: {ext}",
        "ja": "サポートされていない音声形式: {ext}",
        "zh-CN": "不支持的音频格式: {ext}",
        "ko": "지원되지 않는 오디오 형식: {ext}",
        "pl": "Nieobsługiwany format audio: {ext}",
        "tr": "Desteklenmeyen ses formatı: {ext}",
        "ar": "تنسيق صوتي غير مدعوم: {ext}",
        "hi": "असमर्थित ऑडियो फ़ॉर्मेट: {ext}",
        "sv": "Audioformat som inte stöds: {ext}",
    },

    # ── File Lab messages ─────────────────────────────────────────────────
    "FILE_LAB_MSG_NO_INPUT_AUDIO": {
        "value": "No input audio file selected.",
        "en": "No input audio file selected.",
        "es": "No se ha seleccionado ningún archivo de audio de entrada.",
        "fr": "Aucun fichier audio d'entrée sélectionné.",
        "de": "Keine Eingabe-Audiodatei ausgewählt.",
        "pt-BR": "Nenhum arquivo de áudio de entrada selecionado.",
        "it": "Nessun file audio di input selezionato.",
        "nl": "Geen invoer-audiobestand geselecteerd.",
        "ru": "Входной аудиофайл не выбран.",
        "ja": "入力音声ファイルが選択されていません。",
        "zh-CN": "未选择输入音频文件。",
        "ko": "입력 오디오 파일이 선택되지 않았습니다.",
        "pl": "Nie wybrano wejściowego pliku audio.",
        "tr": "Giriş ses dosyası seçilmedi.",
        "ar": "لم يتم تحديد ملف صوتي للإدخال.",
        "hi": "कोई इनपुट ऑडियो फ़ाइल नहीं चुनी गई।",
        "sv": "Ingen inmatningsfil för ljud har valts.",
    },
    "FILE_LAB_MSG_NO_FFMPEG_CONV": {
        "value": "FFmpeg is required for audio conversion.",
        "en": "FFmpeg is required for audio conversion.",
        "es": "FFmpeg es necesario para la conversión de audio.",
        "fr": "FFmpeg est requis pour la conversion audio.",
        "de": "FFmpeg ist für die Audiokonvertierung erforderlich.",
        "pt-BR": "FFmpeg é necessário para conversão de áudio.",
        "it": "FFmpeg è richiesto per la conversione audio.",
        "nl": "FFmpeg is vereist voor audioconversie.",
        "ru": "Для конвертации аудио требуется FFmpeg.",
        "ja": "音声変換にはFFmpegが必要です。",
        "zh-CN": "音频转换需要 FFmpeg。",
        "ko": "오디오 변환에는 FFmpeg이 필요합니다.",
        "pl": "FFmpeg jest wymagany do konwersji audio.",
        "tr": "Ses dönüştürme için FFmpeg gereklidir.",
        "ar": "يلزم FFmpeg لتحويل الصوت.",
        "hi": "ऑडियो कन्वर्ज़न के लिए FFmpeg आवश्यक है।",
        "sv": "FFmpeg krävs för ljudkonvertering.",
    },
    "FILE_LAB_MSG_NO_FILES_COMBINE": {
        "value": "No files to combine.",
        "en": "No files to combine.",
        "es": "No hay archivos para combinar.",
        "fr": "Aucun fichier à combiner.",
        "de": "Keine Dateien zum Zusammenführen.",
        "pt-BR": "Nenhum arquivo para combinar.",
        "it": "Nessun file da combinare.",
        "nl": "Geen bestanden om te combineren.",
        "ru": "Нет файлов для объединения.",
        "ja": "結合するファイルがありません。",
        "zh-CN": "没有要合并的文件。",
        "ko": "결합할 파일이 없습니다.",
        "pl": "Brak plików do połączenia.",
        "tr": "Birleştirilecek dosya yok.",
        "ar": "لا توجد ملفات للدمج.",
        "hi": "कोई फ़ाइल संयोजित करने के लिए नहीं है।",
        "sv": "Inga filer att kombinera.",
    },
    "FILE_LAB_MSG_NO_FFMPEG_COMBINE": {
        "value": "FFmpeg required for audio combine.",
        "en": "FFmpeg required for audio combine.",
        "es": "FFmpeg es necesario para combinar audio.",
        "fr": "FFmpeg requis pour combiner l'audio.",
        "de": "FFmpeg wird zum Zusammenführen von Audio benötigt.",
        "pt-BR": "FFmpeg necessário para combinar áudio.",
        "it": "FFmpeg richiesto per combinare audio.",
        "nl": "FFmpeg vereist voor audio combineren.",
        "ru": "Для объединения аудио требуется FFmpeg.",
        "ja": "音声の結合にはFFmpegが必要です。",
        "zh-CN": "合并音频需要 FFmpeg。",
        "ko": "오디오 결합에는 FFmpeg이 필요합니다.",
        "pl": "FFmpeg wymagany do łączenia audio.",
        "tr": "Ses birleştirme için FFmpeg gereklidir.",
        "ar": "يلزم FFmpeg لدمج الصوت.",
        "hi": "ऑडियो जोड़ने के लिए FFmpeg आवश्यक है।",
        "sv": "FFmpeg krävs för att kombinera ljud.",
    },
}

added = 0
for key, val in NEW.items():
    if key not in data["strings"]:
        data["strings"][key] = val
        added += 1

with open(PATH, "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Done. Added {added} keys. Total: {len(data['strings'])}")
